tests:
    "Product page should be really fast.":
        path: "/product/1"
        assertions:
            - "main.wall_time < 0.5s"
            - "main.peak_memory < 10mb"
            - "metrics.output.network_out < 50kb"
metrics:
    "drupal.cache.invalidate":
        label: "Cache tag invalidation"
        matching_calls:
            php:
                  - callee:
                        selector: '=Drupal\Core\Cache\Cache::invalidateTags'
                        # Each call has different cache tags, separate by them
                        argument: { 1: "^" }
